### ISSUE TITLE
panic: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by zwunix** [iamseth/oracledb_exporter#254]
panic: interface conversion: interface {} is nil, not stringgoroutine 20 [running]:
main.GeneratePrometheusMetrics(0xc000146240, 0xc000010ae0, 0xc00012c320, 0x98, 0x0, 0x0)
	/home/travis/gopath/src/github.com/iamseth/oracledb_exporter/main.go:313 +0x6a0
main.ScrapeGenericValues(0xc000146240, 0xc00016a420, 0xc000148770, 0x8, 0x0, 0x0, 0x0, 0xc0001b8000, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/iamseth/oracledb_exporter/main.go:260 +0x11d
main.ScrapeMetric(0xc000146240, 0xc00016a420, 0xc000148770, 0x8, 0x0, 0x0, 0x0, 0xc0001b8000, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/iamseth/oracledb_exporter/main.go:216 +0xe8
main.(*Exporter).scrape(0xc00012ade0, 0xc00016a420)
	/home/travis/gopath/src/github.com/iamseth/oracledb_exporter/main.go:189 +0x21a
main.(*Exporter).Collect(0xc00012ade0, 0xc00016a420)
	/home/travis/gopath/src/github.com/iamseth/oracledb_exporter/main.go:145 +0x3c
main.(*Exporter).Describe(0xc00012ade0, 0xc00012ae40)
	/home/travis/gopath/src/github.com/iamseth/oracledb_exporter/main.go:137 +0xb0
github.com/iamseth/oracledb_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*registry).Register.func1(0x7ebf80, 0xc00012ade0, 0xc00012ae40)
	/home/travis/gopath/src/github.com/iamseth/oracledb_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:218 +0x3b
created by github.com/iamseth/oracledb_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*registry).Register

**Comment by zwunix** [comment]
[oracle@dsl-db-monitor oracledb_exporter]$ cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)

[oracle@dsl-db-monitor oracledb_exporter]$ uname -a
Linux dsl-db-monitor 5.4.219-1.el7.elrepo.x86_64 #1 SMP Sun Oct 16 10:03:45 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

oracledb version:
oracledb_exporter.0.2.3.linux-amd64.tar.gz
