### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by xiaohaozifeifeifei** [iamseth/oracledb_exporter#411]
After running for a period of time, the following error always occurs, causing the program to exit abnormally.
----------------------------------------------------------------------------------------------------
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x9a825c]

goroutine 46190 [running]:
github.com/iamseth/oracledb_exporter/collector.(*Exporter).scrape.func2()
        /home/runner/work/oracledb_exporter/oracledb_exporter/collector/collector.go:315 +0xffc
created by github.com/iamseth/oracledb_exporter/collector.(*Exporter).scrape
        /home/runner/work/oracledb_exporter/oracledb_exporter/collector/collector.go:321 +0x94e

**Comment by DanielGUO123** [comment]
I had the same problem using Oracle exporter 0.5.1 or 0.5.2 with OS version centos7.9

**Comment by biernatt** [comment]
Same here:

Oracle exporter 0.6.0
OS: "Red Hat Enterprise Linux 9.3 (Plow)"
Platform: OCP

`53panic: runtime error: invalid memory address or nil pointer dereference
54[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x9faf69]
55
56goroutine 4544 [running]:
57github.com/iamseth/oracledb_exporter/collector.(*Exporter).scrape.func2()
58/home/runner/work/oracledb_exporter/oracledb_exporter/collector/collector.go:316 +0x13e9
59created by github.com/iamseth/oracledb_exporter/collector.(*Exporter).scrape in goroutine 36
60/home/runner/work/oracledb_exporter/oracledb_exporter/collector/collector.go:322 +0x776`

**Comment by kellanfan** [comment]
I have the same problem, too.  
docker: Oracle exporter 0.6.0
OS: CentOS Linux release 7.8.2003 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x9fb0e9]

goroutine 43866 [running]:
github.com/iamseth/oracledb_exporter/collector.(*Exporter).scrape.func2()
        /go/src/oracledb_exporter/collector/collector.go:316 +0x13e9
created by github.com/iamseth/oracledb_exporter/collector.(*Exporter).scrape in goroutine 43855
        /go/src/oracledb_exporter/collector/collector.go:322 +0x776
```

**Comment by HansK-p** [comment]
Seems this one might be solved by https://github.com/iamseth/oracledb_exporter/pull/460/

**Comment by duj4** [comment]
@HansK-p The latest one is still 0.6.0 on Apr 6th, this commit was merged (Jul 29th) but not released, any update further?

**Comment by HansK-p** [comment]
We have had no issues after we took the patched version into use some months ago.

**Comment by duj4** [comment]
> We have had no issues after we took the patched version into use some months ago.

Thanks @HansK-p , may I know where/how I could get the patched version?

**Comment by HansK-p** [comment]
I'm not very good with this, so my approach is probably not ideal. I cloned the repo, checked out v0.6.0, probably applied the small change manually based on #460, created the docker image and pushed it to our own container registry.

This might work:
<pre>
git clone https://github.com/iamseth/oracledb_exporter.git
cd oracledb_exporter/
git checkout 0.6.0
vi collector/collector.go # apply PR changes manually
docker build --build-arg BASE_IMAGE=scratch --build-arg VERSION=0.6.0 --build-arg ORACLE_VERSION=19.14 -t oracledb_exporter:0.6.0-patched
</pre> 

Be aware that I haven't double check if the information above is correct, but at least I tried a docker build and it didn't fail. I have not tried to create oracledb_exporter binaries, only containers.

**Comment by duj4** [comment]
> I'm not very good with this, so my approach is probably not ideal. I cloned the repo, checked out v0.6.0, probably applied the small change manually based on #460, created the docker image and pushed it to our own container registry.
> 
> This might work:
> 
> git clone https://github.com/iamseth/oracledb_exporter.git
> cd oracledb_exporter/
> git checkout 0.6.0
> vi collector/collector.go # apply PR changes manually
> docker build --build-arg BASE_IMAGE=scratch --build-arg VERSION=0.6.0 --build-arg ORACLE_VERSION=19.14 -t oracledb_exporter:0.6.0-patched
> Be aware that I haven't double check if the information above is correct, but at least I tried a docker build and it didn't fail. I have not tried to create oracledb_exporter binaries, only containers.

We are running the exporter in VM, the docker version may not help, but thanks a lot for the details, I will open an issue for this.

**Comment by Fanduzi** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x9c8949]
goroutine 247036 [running]:
github.com/iamseth/oracledb_exporter/collector.(*Exporter).scrape.func2()
/Users/TiM/Downloads/GolandProjects/oracledb_exporter/collector/collector.go:317 +0x1429
```

same issue
